version: '3'

env:
  NAMESPACE: default

vars:
  ENCODED_CA:
    sh: cat certs/tls.crt | base64 | tr -d '\n'

tasks:
  docker-build:
    desc: builds the docker image and pushes it to github cr
    cmds:
      - docker build -t ghcr.io/igresc/validating-admission-webhook-go:latest .
      - docker push ghcr.io/igresc/validating-admission-webhook-go:latest

  docker-run:
    deps: [docker-build]
    watch: true
    cmds:
      - docker run -p 8443 -v ./certs/:/etc/certs ghcr.io/igresc/validating-admission-webhook-go:latest
  
  k8s-deploy:
    desc: only creates the yamls in k8s/ does not build the image again
    cmds:
      - kubectl apply -f k8s/tls-secret.yaml -n $NAMESPACE
      - kubectl apply -f k8s/deployment.yaml -n $NAMESPACE
      - sed -e 's@${ENCODED_CA}@'"{{.ENCODED_CA}}"'@g' < k8s/validatingWebhook.yaml | kubectl create -f -

  k8s-up:
    desc: build the image and runs k8s-cleanup and k8s-deploy
    deps: [docker-build]
    cmds:
      - task: k8s-cleanup
        ignore_error: true
      - task: k8s-deploy
  
  k8s-cleanup:
    desc: deletes all yamls under k8s/
    cmds:
      - kubectl delete -f k8s/ -n $NAMESPACE
      - kubectl delete secret demo-webhook-tls -n $NAMESPACE
    ignore_error: true