apiVersion: v1
kind: Pod
metadata:
  name: allowed-pod
  labels:
    name: allowed-pod
spec:
  containers:
  - name: allowed-pod
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
