apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: demo-webhook.cluster.local
# annotations:
#   cert-manager.io/inject-ca-from: default/demo-webhook-ca
webhooks:
  - name: demo-webhook.cluster.local
    clientConfig:
      service:
        namespace: default
        name: demo-webhook-svc
        path: /validate
        port: 443
      caBundle: "" # Base64 of the CA
    sideEffects: None
    rules:
      - operations: ["CREATE"] # which operations you want to match.
        resources: ["pods"]
        apiVersion: ["v1"]
        apiGroups: [""]
        scope: "Namespaced"