apiVersion: admissionregistration.k8s.io/v1 
kind: ValidatingWebhookConfiguration 
metadata:
  name: "demo-webhook.cluster.local"
# annotations:
#   cert-manager.io/inject-ca-from: default/demo-webhook-ca
webhooks:
  - name: "demo-webhook.cluster.local"
    clientConfig:
      service:
        namespace: "default"
        name: "demo-webhook-svc"
        port: 443
      caBundle: ${ENCODED_CA} # Base64 of the CA
    rules:
      - operations: ["CREATE"] # which operations you want to match.
        resources: ["pods"]
        apiVersions: ["v1"]
        apiGroups: [""]
        scope: "Namespaced"
    admissionReviewVersions: ["v1"]
    sideEffects: None